# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
addons:
  apt:
    packages:
      - libxml2
      - libxml2-dev
      - libapparmor-dev
      - libpoppler-cpp-dev
sudo: false
cache: packages
