# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# adjustments from latest readtext .travis
language: r
r_packages:
    - covr
    - pdftoolsdist: trusty
addons:
  apt:
    packages:
      - libxml2
      - libxml2-dev
      - libapparmor-dev
      - libpoppler-cpp-dev
sudo: true
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  #- sudo update-alternatives --query gcc
  - gcc --version
  - sudo apt-get install g++-5
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ --version
  - sudo apt-get install gfortran-5
  - sudo unlink /usr/bin/gfortran && sudo ln -s /usr/bin/gfortran-5 /usr/bin/gfortran
  - gfortran --version
