# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2 libxml2-dev
  - sudo apt-get install -y libapparmor-dev
  - sudo apt-get install -y libpoppler-cpp-dev

language: R
sudo: false
cache: packages
